services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypass
      - MYSQL_DATABASE=mydb
      - MYSQL_PORT=3306
    volumes:
      - .:/app
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: